version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: onlineorder
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - onlineorder-pg-local:/var/lib/postgresql/data
      - ./src/main/resources/database-init.sql:/docker-entrypoint-initdb.d/database-init.sql

    ports:
      - "5432:5432"

volumes:
  onlineorder-pg-local:

