server:
  port: 8080
spring:
  application:
    name: OnlineOrder
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:database-init.sql
logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE